### ISSUE TITLE
No application icon on Linux

### ISSUE THREAD

**Issue by ouuan** [cpeditor/cp-editor#107]
**Describe the bug**

There's no application icon on Linux.

**To Reproduce**

Open the editor, there's no icon.

**Expected behavior**

There should be this icon:

![icon](https://camo.githubusercontent.com/e5f4fd6d34f7b7556a2632b9807b075535650dde/68747470733a2f2f692e696d6775722e636f6d2f33316e397438692e706e67)

**Screenshots**

![screenshot1](https://user-images.githubusercontent.com/30581822/72681452-b9b56b00-3afe-11ea-98b4-57e214f7d5ba.png)

![screenshot2](https://user-images.githubusercontent.com/30581822/72681460-d782d000-3afe-11ea-8551-fedad8a26d6a.png)

(These two screenshots are taken on Manjaro KDE, it's different on Ubuntu.)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04 & 18.04 LTS, Manjaro KDE 18.1.5
 - Version: 5.1.0

**Smartphone (please complete the following information):**

N/A

**Additional context**

N/A

**Comment by coder3101** [comment]
That icon is for Xorg, Can you confirm that other AppImages show their Icons when lanuched. Try any GUI based app image and let me know it. Sadly, I also do not have any Linux setup to test it.

**Comment by ouuan** [comment]
It seems that it's not easy to set icons for AppImages, but it's not impossible. Some research required.

**Comment by testitem** [comment]
No icons show for me at least

**Comment by ouuan** [comment]
Seems that there is an icon on Mac now because `dmg` is packed.

**Comment by coder3101** [comment]
Yes, and as discussed for Linux AppImage the icon will come only if user has installed AppImage daemon tool. So this also should be closed

**Comment by ouuan** [comment]
It may be difficult to set icons for AppImages, but `setWindowIcon` will simply do in Qt!

**Comment by ouuan** [comment]
Added in ecf7d4c60bac780c3f08ced129c022fc70af89cc.
