### ISSUE TITLE
Enable/Disable test cases

### ISSUE THREAD

**Issue by ouuan** [cpeditor/cp-editor#177]
**Is your feature request related to a problem? Please describe.**

If I only want to run a subset of test cases, it will be a waste to run the others, and it will be hard to read the stderrs with many test cases mixed up.

**Describe the solution you'd like**

Make it able to enable/disable test cases. I've considered about three solutions:

1. All test cases are enabled by default, you can toggle enable/disable for each of them.
2. You can either disable test cases or "solo" some of them. If there are "solo" test cases, only these test cases will be enabled. Otherwise, the test cases which are not manually disabled will be enabled. (Just like some audio editing software.)
3. Add a button for running a particular test case.

I think the second one is the best. And 2 and 3 can be mixed, that could be even better.

And it should be good to make a drop-down menu for each test case.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by coder3101** [comment]
@ouuan +1

**Comment by ouuan** [comment]
Enable/disable/invert all is also good.

**Comment by ouuan** [comment]
Also: enable WA (only/additional), enable WA and UNKNOWN (only/additional), disable AC (additional).

**Comment by ouuan** [comment]
Added in 274e07939a90499dc956976673ce17f7dfdae86b.
