### ISSUE TITLE
Color option enchancement

### ISSUE THREAD

**Issue by nikhil-sarda** [cpeditor/cp-editor#179]
**Describe the bug**

"Red" color is for wrong answer.It works fine for that.But also green color should be given for both "Accepted" and "Prestests Passed".

I was finding my mistake in code wondering why its wrong as it was red in color(with pretests passed verdict).

**To Reproduce**

Submit the solution in a contest when only pretests are judged.

**Screenshots**

**Environment**

 - OS: [e.g. Windows 10]
 - Version: [e.g. 5.9.4]

**Additional context**

**Comment by ouuan** [comment]
Do you think we need to release this before v6.0?

**Comment by ouuan** [comment]
I guess you are using Windows (from your screenshots in other issues), if you want to use the latest version, you can download the [Artifact](https://github.com/cpeditor/cp-editor/suites/477917248/artifacts/2168746) and replace your .exe file with it.

**Comment by coder3101** [comment]
> Do you think we need to release this before v6.0?

I think it should directly be released in 6.0.0, there is no testing required!

**Comment by ouuan** [comment]
This was finally fixed in 2fbaac003e0d56afd7f459e3496531add4ff735b. (Seems that testing is required.)

**Comment by coder3101** [comment]
@nikhil-sarda 
Could you please test it in any contest and let us know if it's fixed? If it isn't reopen this issue!

**Comment by ouuan** [comment]
I believe it's fixed (I used 2 minutes during [Codeforces Round #625](https://codeforces.com/contest/1320) to fix it after discovering that it should be "Pretests passed" instead of "Pretests Passed").

**Comment by nikhil-sarda** [comment]
> I believe it's fixed (I used 2 minutes during [Codeforces Round #625](https://codeforces.com/contest/1320) to fix it after discovering that it should be "Pretests passed" instead of "Pretests Passed").

Yes,i am sorry for not being that exact.I checked its "Pretests passed"

**Comment by nikhil-sarda** [comment]
> I believe it's fixed (I used 2 minutes during [Codeforces Round #625](https://codeforces.com/contest/1320) to fix it after discovering that it should be "Pretests passed" instead of "Pretests Passed").

But what you changed (in the code)contains capital letter yet?

**Comment by nikhil-sarda** [comment]
> @nikhil-sarda
> Could you please test it in any contest and let us know if it's fixed? If it isn't reopen this issue!

I will confirm and reply after the next contest I give.
