### ISSUE TITLE
Unexpected behavior of diff viewer in version 6.0.1

### ISSUE THREAD

**Issue by Ravenclaw-OIer** [cpeditor/cp-editor#181]
**Describe the bug**

The diff viewer is not showing line breaks, instead it's shown as some spaces.

**To Reproduce**

1. Choose a random problem, get some inputs and outputs
2. Select any checker you wish
3. Click the button that triggers the diff viewer
4. You can see that the diff viewer does not show line breaks.

**Screenshots**

![screenshot](https://i.loli.net/2020/02/26/G3TU4KIp72Rnuz8.png)

**Environment**

 - OS: Windows 10
 - Version: 6.0.1

**Additional context**

**Comment by Ravenclaw-OIer** [comment]
Sorry my bad, didn't see the display new line is set to "off" on default.

**Comment by ouuan** [comment]
It IS unexpected.

https://github.com/cpeditor/cp-editor/blob/6a6f55c06c8fbf495bdfa2cae8f29806d54b4b1b/src/Widgets/TestCases.cpp#L404-L405

If this option is checked, `\n` should be replaced by `<br>`.

**Comment by ouuan** [comment]
@allcontributors add @Ravenclaw-OIer as a contributor for ideas and bug reports.
