### ISSUE TITLE
Make the window of cpeditor resizable to atleast half the screen.

### ISSUE THREAD

**Issue by nikhil-sarda** [cpeditor/cp-editor#183]
**Is your feature request related to a problem? Please describe.**
The smallest possible resizing of the editor is more than half the screen. It would be cooler and more convinient if it would be resizable to atleast half, so that we can open the contest page of the rest half of our screen.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ouuan** [comment]
It can be resized to about 800px in split view mode, which fits the half of a 1920*1080 screen. You can use the editor view mode (View → Editor Mode) if your screen resolution is smaller than 1920*1080.

Reopen this if the editor mode doesn't work for you.

It's better to provide a screenshot if you think we should work on this.

**Comment by ouuan** [comment]
The editor mode may not work for resizing narrower in 5.9.7, you can use 6.0.2 instead.
