### ISSUE TITLE
Close option not working in find and replace

### ISSUE THREAD

**Issue by nikhil-sarda** [cpeditor/cp-editor#185]
**Describe the bug**
I just used find and replace for the first time.It worked fine but the close option isn't working.The popup remains.

**To Reproduce**
Press ctrl+F and replace whatever required.But can't close it now.The popup remains. 

**Screenshots**

**Environment**

 - OS: Win 10
 - Version: [e.g. 5.9.4]

**Additional context**

**Comment by coder3101** [comment]
@nikhil-sarda Fixed in 6.0.2 (Please check that version). In the meantime you can press ESC to close it forcefully.

**Comment by coder3101** [comment]
@nikhil-sarda If you can confirm that it has been fixed in latest beta or latest stable. please close the issue yourself. We know this is a big issue but we failed to rollout a fix to stable because

**Comment by nikhil-sarda** [comment]
> @nikhil-sarda If you can confirm that it has been fixed in latest beta or latest stable. please close the issue yourself. We know this is a big issue but we failed to rollout a fix to stable because

because?

**Comment by ouuan** [comment]
Because the versioning rule changed, and it's hard to maintain v5.9 now.

**Comment by coder3101** [comment]
@nikhil-sarda because this issue only occur on windows, and version rules changed. But from 6.0, everything should be nicely patched and pushed!

**Comment by ouuan** [comment]
However, after this versioning rule change, the versions will be more clear, and no more as confusing as before.

**Comment by nikhil-sarda** [comment]
Its working in the latest beta perfectly.Thanks!
